# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uwaterloo Indoor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    use_frameworks!

  # Pods for Uwaterloo Indoor
    pod 'IndoorAtlas'


  target 'Uwaterloo IndoorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Uwaterloo IndoorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
