USE [master]
GO

/****** Object:  Database [GeoWcf]    Script Date: 2017/12/22 下午 03:11:00 ******/
CREATE DATABASE [GeoWcf]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GeoWcf', FILENAME = N'D:\RDSDBDATA\DATA\GeoWcf.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'GeoWcf_log', FILENAME = N'D:\RDSDBDATA\DATA\GeoWcf_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GeoWcf] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GeoWcf].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GeoWcf] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GeoWcf] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GeoWcf] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GeoWcf] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GeoWcf] SET ARITHABORT OFF 
GO

ALTER DATABASE [GeoWcf] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GeoWcf] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GeoWcf] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GeoWcf] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GeoWcf] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GeoWcf] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GeoWcf] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GeoWcf] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GeoWcf] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GeoWcf] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GeoWcf] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GeoWcf] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GeoWcf] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GeoWcf] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GeoWcf] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GeoWcf] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GeoWcf] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GeoWcf] SET RECOVERY FULL 
GO

ALTER DATABASE [GeoWcf] SET  MULTI_USER 
GO

ALTER DATABASE [GeoWcf] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GeoWcf] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GeoWcf] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GeoWcf] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GeoWcf] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GeoWcf] SET QUERY_STORE = OFF
GO

USE [GeoWcf]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GeoWcf] SET  READ_WRITE 
GO


